#include<stdio.h>
#include<math.h>
/*
Author: anuavrag1912 
Program to parse Intel8hex files that are generated by AVR-GCC and print memory and data values;
Address range from 0 to 65,535
*/
unsigned short hextodecimal(char *, unsigned int);
unsigned char asciitohex(unsigned char);
struct org{
	unsigned char byte[2];
	unsigned char address[4];
	unsigned char record[2];
};
int main()
{
	FILE *fp;
	fp = fopen("led-boot.hex","rb");
	
	 int ch=0;
	
	unsigned short address=0;
	
	unsigned char count=0;
	
	unsigned char record=0;  
	unsigned long bytes=0;
	printf("\nAddress:\tInstruction:\n");
	
	struct org s;
	while(ch!=EOF)
	{	ch = fgetc(fp);	
		//First character of line is always ':'
		ch =fgetc(fp);
		s.byte[0] = asciitohex(ch);
		ch=fgetc(fp);	
		s.byte[1] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[0] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[1] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[2] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[3] = asciitohex(ch);
		ch=fgetc(fp);
		s.record[0] = asciitohex(ch);
		ch=fgetc(fp);
		s.record[1] = asciitohex(ch);
		count = 	hextodecimal(s.byte,2);
		address = 	hextodecimal(s.address,4);
		record = 	hextodecimal(s.record, 2);
	if(record==0)
	{
		bytes+=count;
		//printf("%x\t%x\n",address, opcode);

		
		while(count>0)
		{	
		unsigned char opcode[2];
		ch = fgetc(fp);
		opcode[0] = asciitohex(ch);
		ch = fgetc(fp);
		opcode[1] = asciitohex(ch);
		unsigned short op = hextodecimal(opcode,2);
		count--;	
		printf("%4x \t %4x\n",address,op);
		address++;
			
		}
	
	}
	
	else if(record==01)							//record =01 End of hex file
	break;
	
	while(ch!='\n')
	ch=fgetc(fp);			
	}
	unsigned char buffer[bytes];
	unsigned long i = 0;
	rewind(fp);
	ch=0;
	while(ch!=EOF)
	{	ch = fgetc(fp);	
		//First character of line is always ':'
		ch =fgetc(fp);
		s.byte[0] = asciitohex(ch);
		ch=fgetc(fp);	
		s.byte[1] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[0] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[1] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[2] = asciitohex(ch);
		ch=fgetc(fp);
		s.address[3] = asciitohex(ch);
		ch=fgetc(fp);
		s.record[0] = asciitohex(ch);
		ch=fgetc(fp);
		s.record[1] = asciitohex(ch);
		count = 	hextodecimal(s.byte,2);
		address = 	hextodecimal(s.address,4);
		record = 	hextodecimal(s.record, 2);
	if(record==0)
	{
		//bytes+=count;
		//printf("%x\t%x\n",address, opcode);

		
		while(count>0)
		{	
		unsigned char opcode[2];
		ch = fgetc(fp);
		opcode[0] = asciitohex(ch);
		ch = fgetc(fp);
		opcode[1] = asciitohex(ch);
		unsigned short op = hextodecimal(opcode,2);
		buffer[i++] = op;
		count--;	
		//printf("%4x \t %4x\n",address,op);
		//address++;
			
		}
	
	}
	
	else if(record==01)							//record =01 End of hex file
	break;
	
	while(ch!='\n')
	ch=fgetc(fp);			
	}
	
	
	
	printf("\n");
	/*
	for(i=0;i<bytes;i++)
	printf("%x\n",buffer[i]);
	*/
	printf("Total bytes to write: %u\n",bytes);
	printf("Total words to write to flash: %u",bytes/2);
	fclose(fp);
	
	
	
	return 0;
}
unsigned short hextodecimal(char *ptr, unsigned int no)
{	int i=0;
	unsigned short dec=0;
	for(i=0;i<no;i++)
	{
		dec +=(pow(16,no-i-1)*ptr[i]);
		
	}
	
	return dec;
} 

unsigned char asciitohex(unsigned char ch){
	
	if(ch>='0' && ch<='9')
	{
		return (ch-'0');
	}
	
	else
	{
	return ((ch-'A' )+ 10);	
	}
	
}
